sudo: required
branches:
  only:
  - develop
services:
  - docker

before_install:
  - docker build -t test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true test npm run test

after_success:
  - docker build -t davidq25/mlt-frontend ./client
  - docker build -t davidq25/mlt-backend ./server
  - docker build -t davidq25/mlt-nginx ./nginx
  - docker build -t davidq25/mlt-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push davidq25/mlt-frontend
  - docker push davidq25/mlt-backend
  - docker push davidq25/mlt-nginx
  - docker push davidq25/mlt-worker

