version: "3"
services:
    nginx:
        depends_on: 
            - frontend
            - backend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports: 
            - "3050:80"
    postgresDB:
        image: "postgres:latest"
        environment: 
            - POSTGRES_PASSWORD=postgres
    redisServer:
        image: "redis:latest"
    frontend:
        stdin_open: true
        ports: 
            - '3000:80'
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes: 
            - /app/node_modules
            - ./client:/app
    backend:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redisServer
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgresDB
            - PGDATABASE=postgres
            - PGPASSWORD=postgres
            - PGPORT=5432
    worker:     
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redisServer
            - REDIS_PORT=6379
        
